version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: banco_postgres
    environment:
      POSTGRES_DB: messages
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

volumes:
  data:
