spring:
  application:
    name: App

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: springframework.kafka.support.serializer.ErrorHandlingSerializer
      value-serializer: springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: chat-group-ui
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serializer.JsonSerializer


  datasource:
    url: jdbc:postgresql://localhost:5432/messages
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
